# Generated by Django 5.0.1 on 2024-01-13 02:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0004_remove_demonstracaoderesultados_ano_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="demonstracaoderesultados",
            name="ano",
            field=models.CharField(blank=True, default="2015", max_length=50),
        ),
        migrations.AlterField(
            model_name="demonstracaoderesultados",
            name="EBIT",
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20),
        ),
        migrations.AlterField(
            model_name="demonstracaoderesultados",
            name="EBITIDA",
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20),
        ),
        migrations.AlterField(
            model_name="demonstracaoderesultados",
            name="dividendo_declarados_e_pagos",
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20),
        ),
        migrations.AlterField(
            model_name="demonstracaoderesultados",
            name="lucro_antes_de_imposto",
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20),
        ),
        migrations.AlterField(
            model_name="demonstracaoderesultados",
            name="lucro_liquido_depois_de_imposto",
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20),
        ),
        migrations.AlterField(
            model_name="demonstracaoderesultados",
            name="lucros_bruto",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0.0, max_digits=20
            ),
        ),
        migrations.AlterField(
            model_name="demonstracaoderesultados",
            name="numero_medio_ponderado_de_acoes",
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20),
        ),
        migrations.AlterField(
            model_name="demonstracaoderesultados",
            name="vendas",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0.0, max_digits=20
            ),
        ),
    ]
