# Generated by Django 5.0.1 on 2024-01-20 12:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0005_demonstracaoderesultados_ano_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Noticias",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "noticia",
                    models.CharField(default="texto da noticia", max_length=600),
                ),
                (
                    "imagens",
                    models.ImageField(
                        default="imagens/no_image.jpg", upload_to="imagens/"
                    ),
                ),
                (
                    "link_video",
                    models.CharField(default="https://www.youtube.com", max_length=300),
                ),
                (
                    "titulo",
                    models.CharField(default="titulo da noticia", max_length=300),
                ),
                ("corpo", models.CharField(default="Desenvolvimento", max_length=3000)),
            ],
            options={
                "verbose_name": "Noticia",
                "verbose_name_plural": "Noticias",
                "ordering": ("titulo",),
            },
        ),
    ]
