# Generated by Django 5.0.1 on 2024-01-20 12:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0006_noticias"),
    ]

    operations = [
        migrations.AddField(
            model_name="noticias",
            name="date",
            field=models.DateField(blank=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
