# Generated by Django 5.0.1 on 2024-01-20 13:05

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0007_noticias_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="noticias",
            name="date",
            field=models.DateField(blank=True, default=django.utils.timezone.now),
        ),
    ]
