# Generated by Django 5.0.1 on 2024-01-20 14:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0008_alter_noticias_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="noticias",
            name="sector_da_noticia",
            field=models.CharField(
                choices=[
                    ("economia", "Economia"),
                    ("negocios", "Negócios"),
                    ("politica", "Política"),
                    ("tecnologias", "Tecnologias"),
                    ("petroleo-e-gas", "Petróleo e Gás"),
                    ("opiniao", "Opinião"),
                    ("datas-importantes", "Datas-Importantes"),
                ],
                default="economia",
                max_length=100,
            ),
        ),
    ]
