# Generated by Django 5.0.2 on 2024-02-07 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_cotacoesdasacoes_numero_de_accoes_negociadas_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticias',
            name='imagens',
            field=models.CharField(default='Coloque a url da imagem', max_length=3000),
        ),
    ]
