# Generated by Django 5.0.2 on 2024-02-07 22:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_visualizacaonoticia'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VisualizacaoNoticia',
        ),
    ]
