# Generated by Django 5.0.2 on 2024-02-07 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_delete_visualizacaonoticia'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstatisticasVisualizacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_visualizacoes', models.IntegerField(default=0)),
                ('visitantes_unicos', models.IntegerField(default=0)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
