# Generated by Django 5.0.2 on 2024-02-09 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_estatisticasvisualizacao_ip_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='company_logo',
            field=models.ImageField(default='static/media/company_logs/no_image.png', upload_to='static/media/company_logs/'),
        ),
    ]
