# Generated by Django 5.0.2 on 2024-02-09 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_alter_company_company_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='abreviatura',
            field=models.CharField(default='CDM', max_length=100),
        ),
    ]
