# Generated by Django 5.0.2 on 2024-02-09 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_company_abreviatura'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='company_logo',
            field=models.ImageField(default='company_logs/no_image.png', upload_to='company_logs/'),
        ),
    ]
