# Generated by Django 5.0.2 on 2024-02-09 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_company_codigo_isin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='company_logo',
            field=models.ImageField(default='static/media/company_logs/no_image.png', upload_to='static/media/company_logs/'),
        ),
        migrations.AlterField(
            model_name='noticias',
            name='imagens',
            field=models.ImageField(default='static/media/noticias/no_image.png', upload_to='static/media/noticias/'),
        ),
    ]
