# Generated by Django 5.0.2 on 2024-02-10 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_alter_company_company_logo_alter_noticias_imagens'),
    ]

    operations = [
        migrations.CreateModel(
            name='Corretoras',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Nome da Corretora', max_length=40)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=50)),
                ('nome_do_arquivo', models.CharField(max_length=255)),
                ('arquivo', models.FileField(upload_to='static/media/pdf/')),
                ('imagem', models.ImageField(upload_to='static/media/corretoras/')),
                ('link_da_corretora', models.URLField()),
            ],
            options={
                'verbose_name': 'Corretora',
                'verbose_name_plural': 'Corretoras',
                'ordering': ('id',),
            },
        ),
    ]
