# Generated by Django 5.0.2 on 2024-02-10 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_corretoras'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='corretoras',
            name='nome_do_arquivo',
        ),
        migrations.AddField(
            model_name='corretoras',
            name='outros_arquivos',
            field=models.FileField(default='static/media/zip/outros_documentos.zip', upload_to='static/media/zip/'),
        ),
    ]
