# Generated by Django 5.0.2 on 2024-02-11 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_remove_corretoras_nome_do_arquivo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='corretoras',
            name='email',
        ),
        migrations.RemoveField(
            model_name='corretoras',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='corretoras',
            name='email_1',
            field=models.EmailField(default='email@gmail.com', max_length=254),
        ),
        migrations.AddField(
            model_name='corretoras',
            name='email_2',
            field=models.EmailField(default='email@gmail.com', max_length=254),
        ),
        migrations.AddField(
            model_name='corretoras',
            name='email_3',
            field=models.EmailField(default='email@gmail.com', max_length=254),
        ),
        migrations.AddField(
            model_name='corretoras',
            name='nome_do_phone_1',
            field=models.CharField(default='nome', max_length=30),
        ),
        migrations.AddField(
            model_name='corretoras',
            name='nome_do_phone_2',
            field=models.CharField(default='nome', max_length=30),
        ),
        migrations.AddField(
            model_name='corretoras',
            name='nome_do_phone_3',
            field=models.CharField(default='nome', max_length=30),
        ),
        migrations.AddField(
            model_name='corretoras',
            name='phone_number_1',
            field=models.CharField(default='numero de telefone', max_length=50),
        ),
        migrations.AddField(
            model_name='corretoras',
            name='phone_number_2',
            field=models.CharField(default='numero de telefone', max_length=50),
        ),
        migrations.AddField(
            model_name='corretoras',
            name='phone_number_3',
            field=models.CharField(default='numero de telefone', max_length=50),
        ),
    ]
