# Generated by Django 5.0.2 on 2024-02-11 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_remove_corretoras_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corretoras',
            name='email_1',
            field=models.EmailField(default='-', max_length=254),
        ),
        migrations.AlterField(
            model_name='corretoras',
            name='email_2',
            field=models.EmailField(default='-', max_length=254),
        ),
        migrations.AlterField(
            model_name='corretoras',
            name='email_3',
            field=models.EmailField(default='-', max_length=254),
        ),
        migrations.AlterField(
            model_name='corretoras',
            name='nome_do_phone_1',
            field=models.CharField(default='-', max_length=30),
        ),
        migrations.AlterField(
            model_name='corretoras',
            name='nome_do_phone_2',
            field=models.CharField(default='-', max_length=30),
        ),
        migrations.AlterField(
            model_name='corretoras',
            name='nome_do_phone_3',
            field=models.CharField(default='-', max_length=30),
        ),
        migrations.AlterField(
            model_name='corretoras',
            name='phone_number_1',
            field=models.CharField(default='-', max_length=50),
        ),
        migrations.AlterField(
            model_name='corretoras',
            name='phone_number_2',
            field=models.CharField(default='-', max_length=50),
        ),
        migrations.AlterField(
            model_name='corretoras',
            name='phone_number_3',
            field=models.CharField(default='-', max_length=50),
        ),
    ]
