# Generated by Django 5.0.2 on 2024-02-11 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0024_alter_corretoras_email_1_alter_corretoras_email_2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corretoras',
            name='email_1',
            field=models.CharField(default='-', max_length=30),
        ),
        migrations.AlterField(
            model_name='corretoras',
            name='email_2',
            field=models.CharField(default='-', max_length=30),
        ),
        migrations.AlterField(
            model_name='corretoras',
            name='email_3',
            field=models.CharField(default='-', max_length=30),
        ),
    ]
